### ISSUE TITLE
double-free from LoadCertificateMem caused by repo update race

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2929]
There is a race condition between the TryFinish() path in the fuse handlers and the Check(dryrun=true) in the CheckSynchronously() of the notification thread. Both try to reload the certificate, and can cause a double-free.

Steps to reproduce:

* set up a repo with a short catalog update polling time
* set up a transaction/publish in a continuous loop 
* mount the repo, and put some cvmfs load on it
* run `cvmfs_talk remount sync` in a continuous loop  
* wait (perhaps along time)

Observe that eventually the client will crash. The stack trace will show something like:
```
Thread 21 (Thread 0x7fff6e14d700 (LWP 48499)):
#0  0x00007ffff6ec3993 in select () from /lib64/libc.so.6
#1  0x00007ffff45ab696 in SafeSleepMs (ms=ms@entry=100)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/util/posix.cc:1730
#2  0x00007ffff4583241 in Watchdog::SendTrace (sig=6, 
    siginfo=<optimized out>, context=<optimized out>)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/monitor.cc:317
#3  <signal handler called>
#4  0x00007ffff6e04377 in raise () from /lib64/libc.so.6
#5  0x00007ffff6e05a68 in abort () from /lib64/libc.so.6
#6  0x00007ffff6e46ec7 in __libc_message () from /lib64/libc.so.6
#7  0x00007ffff6e4f6b9 in _int_free () from /lib64/libc.so.6
#8  0x00007ffff651f80d in CRYPTO_free () from /lib64/libcrypto.so.10
#9  0x00007ffff660951d in ASN1_STRING_free () from /lib64/libcrypto.so.10
#10 0x00007ffff65fd5fd in ASN1_primitive_free () from /lib64/libcrypto.so.10
#11 0x00007ffff65fd97f in ASN1_template_free () from /lib64/libcrypto.so.10
#12 0x00007ffff65fd80a in asn1_item_combine_free ()
   from /lib64/libcrypto.so.10
#13 0x00007ffff65fd8c5 in ASN1_item_free () from /lib64/libcrypto.so.10
#14 0x00007ffff459f345 in signature::SignatureManager::LoadCertificateMem (
    this=this@entry=0x7fff306f6930, 
    buffer=0x7fff2c001b60 "-----BEGIN CERTIFICATE-----\n......."..., 
    buffer_size=1078)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/signature.cc:248
#15 0x00007ffff4581e43 in manifest::DoVerify (manifest_data=<optimized out>, 
    manifest_size=572, base_url="", 
    repository_name="....", 
    minimum_timestamp=minimum_timestamp@entry=1639495806, 
    base_catalog=base_catalog@entry=0x7fff6e14cc18, 
    signature_manager=0x7fff306f6930, download_manager=0x7fff3006f330, 
    ensemble=0x7fff6e14cc78)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/manifest_fetch.cc:94
#16 0x00007ffff45822f8 in manifest::DoFetch (base_url="", 
    repository_name="....", 
    minimum_timestamp=minimum_timestamp@entry=1639495806, 
    base_catalog=base_catalog@entry=0x7fff6e14cc18, 
    signature_manager=signature_manager@entry=0x7fff306f6930, 
    download_manager=download_manager@entry=0x7fff3006f330, 
    ensemble=0x7fff6e14cc78)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/manifest_fetch.cc:183
#17 0x00007ffff45823ad in manifest::Fetch (base_url="", 
    repository_name=".....", 
    minimum_timestamp=minimum_timestamp@entry=1639495806, 
    base_catalog=base_catalog@entry=0x7fff6e14cc18, 
    signature_manager=signature_manager@entry=0x7fff306f6930, 
    download_manager=download_manager@entry=0x7fff3006f330, 
    ensemble=0x7fff6e14cc78)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/manifest_fetch.cc:197
#18 0x00007ffff4546e33 in catalog::ClientCatalogManager::LoadCatalog (
    this=this@entry=0x7fff300562d0, mountpoint=..., hash=..., 
    catalog_path=catalog_path@entry=0x0, catalog_hash=0x7fff6e14cbfc, 
    catalog_hash@entry=0x0)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/catalog_mgr_client.cc:168
#19 0x00007ffff45c6a0e in catalog::AbstractCatalogManager<catalog::Catalog>::Remount (this=0x7fff300562d0, dry_run=dry_run@entry=true)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/catalog_mgr_impl.h:122
#20 0x00007ffff45c60b3 in FuseRemounter::Check (
    this=this@entry=0x7fff32e02850)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/fuse_remount.cc:85
#21 0x00007ffff45c62cf in FuseRemounter::MainRemountTrigger (
    data=0x7fff32e02850)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/fuse_remount.cc:225
#22 0x00007ffff79c2ea5 in start_thread () from /lib64/libpthread.so.0
#23 0x00007ffff6ecc8cd in clone () from /lib64/libc.so.6
```

This can be fixed with a lock on access to `lock_certificate_` in `signature.cc`

**Comment by mharvey-jt** [comment]
https://github.com/cvmfs/cvmfs/pull/2930
