### ISSUE TITLE
double-free from Manifest from race on repo update

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2932]
Similar to #2929, a race between CheckSynchronously() and polled repo updates can cause this double-free the Manifest class.  Can be fixed with a writelock guard around LoadCatalog() https://github.com/cvmfs/cvmfs/pull/2931

```
Thread 19 (Thread 0x7fffd6ffd700 (LWP 56374)):
#0  0x00007ffff6ec3993 in select () from /lib64/libc.so.6
#1  0x00007ffff45a9b74 in SafeSleepMs (ms=ms@entry=100)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/util/posix.cc:1730
#2  0x00007ffff45813a9 in Watchdog::SendTrace (sig=6, 
    siginfo=<optimized out>, context=<optimized out>)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/monitor.cc:321
#3  <signal handler called>
#4  0x00007ffff6e04377 in raise () from /lib64/libc.so.6
#5  0x00007ffff6e05a68 in abort () from /lib64/libc.so.6
#6  0x00007ffff6e46ec7 in __libc_message () from /lib64/libc.so.6
#7  0x00007ffff6e4f6b9 in _int_free () from /lib64/libc.so.6
#8  0x00007ffff7771b63 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() () from /lib64/libstdc++.so.6
#9  0x00007ffff4546141 in ~Manifest (this=0x7fffc800b0c0, 
    __in_chrg=<optimized out>)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/manifest.h:41
#10 UniquePtr<manifest::Manifest>::Free (this=this@entry=0x13c32e8)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/util/pointer.h:68
#11 0x00007ffff4545070 in Free (this=0x13c32e8)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/util/pointer.h:50
#12 operator= (ref=0x7fffc800b1c0, this=0x13c32e8)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/util/pointer.h:38
#13 catalog::ClientCatalogManager::LoadCatalog (this=this@entry=0x13c3150, 
    mountpoint=..., hash=..., catalog_path=catalog_path@entry=0x0, 
    catalog_hash=0x7fffd6ffc8ec, catalog_hash@entry=0x0)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/catalog_mgr_client.cc:205
#14 0x00007ffff45c4f0c in catalog::AbstractCatalogManager<catalog::Catalog>::Remount (this=0x13c3150, dry_run=dry_run@entry=true)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/catalog_mgr_impl.h:122
#15 0x00007ffff45c45b1 in FuseRemounter::Check (this=this@entry=0x1440d50)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/fuse_remount.cc:85
#16 0x00007ffff45c4d73 in FuseRemounter::CheckSynchronously (this=0x1440d50)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/fuse_remount.cc:136
#17 0x00007ffff45c8aea in KafkaNotificationClient::Consume (
    this=this@entry=0x1441110, repo_name="...", 
    msg_text="{\"repository\":\"...\",\"revision\":1096202,\"rootHash\":\"XXXXXC\"}")
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/kafka_notification_client.cc:51
#18 0x00007ffff45c8cef in KafkaNotificationClient::Run (data=0x1441110)
    at /builddir/build/BUILD/cvmfs-2.8.1/cvmfs/kafka_notification_client.cc:196
#19 0x00007ffff79c2ea5 in start_thread () from /lib64/libpthread.so.0
#20 0x00007ffff6ecc8cd in clone () from /lib64/libc.so.6
```

**Comment by HereThereBeDragons** [comment]
closing for now, please reopen if it occurs again
