### ISSUE TITLE
cvmfs overwhelmed by concurrent open()s

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3099]
Noticed a partial failure mode today, wherein a cvmfs mount   with a large number of concurrent open()s overwhelmed the cache daemon.
At peak, the cvmfs2 mount process had ~2800(sic) fuse threads, which were blocked talking to the cache manager: 
```Thread 2885 (Thread 0x7ff00a815700 (LWP 121056)):
#0  0x00007ffff79c1847 in write () from /lib64/libpthread.so.0
#1  0x00007ffff5a2c395 in WritePipe (fd=7, buf=buf@entry=0x7ff00a814540, nbyte=nbyte@entry=48) at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/util/posix.cc:521
#2  0x00007ffff5a1a576 in PosixQuotaManager::Touch (this=0x641320, hash=...) at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/quota_posix.cc:1882
#3  0x00007ffff59bfe5f in PosixCacheManager::Open (this=this@entry=0x642390, object=...) at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/cache_posix.cc:363
#4  0x00007ffff59e688c in cvmfs::Fetcher::OpenSelect (this=this@entry=0x85f720, id=..., name="/modules/jump/rpms/el8/Python-2.7.18/version/16448/Python-2.7.18/lib/python2.7/unittest/case.py", object_type=object_type@entry=CacheManager::kTypeRegular) at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/cache.h:91
#5  0x00007ffff59e730a in cvmfs::Fetcher::Fetch (this=this@entry=0x85f720, repo_name="modules.firm.jump.gcp", id=..., size=size@entry=42765, name="/modules/jump/rpms/el8/Python-2.7.18/version/16448/Python-2.7.18/lib/python2.7/unittest/case.py", compression_algorithm=compression_algorithm@entry=zlib::kZlibDefault, object_type=CacheManager::kTypeRegular, alt_url="", range_offset=-1) at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/fetch.cc:152
#6  0x00007ffff5a41423 in cvmfs::cvmfs_open (req=0x7ffc2c807d20, ino=345957468, fi=0x7ff00a814d30) at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/mountpoint.h:450
#7  0x00007ffff6a82080 in loader::stub_open (req=0x7ffc2c807d20, ino=345957468, fi=0x7ff00a814d30) at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/loader.cc:265
#8  0x00007ffff60d8908 in do_open () from /lib64/libfuse3.so.3
#9  0x00007ffff60d943a in fuse_session_process_buf_int () from /lib64/libfuse3.so.3
#10 0x00007ffff60d4b75 in fuse_do_work () from /lib64/libfuse3.so.3
#11 0x00007ffff79b814a in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff6dbaf23 in clone () from /lib64/libc.so.6
```
while ~ 10 threads were blocked obtaining an AbstractCatalogManager rdlock.

`strace`ing the cache process showed it continually reading and writing to the cache sqlite3 db. The io load on the backing storage for that (a SATA SSD) wasn't at all high, so it didn't seem like that IO was the bottleneck.

there were consistently ~ 180k fds open by cvmfs2, but only ~30k open on the cvmfs fs by client processes.

The problem persisted for ~ 3 hours, but then cleared spontaneously within a few seconds. There wasn't any apparent change the the user process load at that time.

**Comment by HereThereBeDragons** [comment]
closing for now. please reopen if it still occurs
