### ISSUE TITLE
assert from `glue::PageCacheTracker::Close `

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3135]
2.8.1. Looks like the assert() is still present in -devel. As with other asserts, it blows up the mount point causing a service outage.

```
Thread 24 (Thread 0x7ffef97fa700 (LWP 41982)):
#0  0x00007ffff6db24ff in select () from /lib64/libc.so.6
#1  0x00007ffff5a2d1df in SafeSleepMs (ms=ms@entry=100)
    at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/util/posix.cc:1730
#2  0x00007ffff5a07316 in Watchdog::SendTrace (sig=<optimized out>,
    siginfo=<optimized out>, context=<optimized out>)
    at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/monitor.cc:321
#3  <signal handler called>
#4  0x00007ffff6cf57ff in raise () from /lib64/libc.so.6
#5  0x00007ffff6cdfc35 in abort () from /lib64/libc.so.6
#6  0x00007ffff6cdfb09 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#7  0x00007ffff6cedde6 in __assert_fail () from /lib64/libc.so.6
#8  0x00007ffff59ebf24 in glue::PageCacheTracker::Close (this=0x8a2180,
    inode=<optimized out>, inode@entry=1422137387)
    at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/glue_buffer.cc:398
#9  0x00007ffff5a3bff8 in cvmfs::cvmfs_release (req=0x7fff4020ccc0,
    ino=1422137387, fi=<optimized out>)
    at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/mountpoint.h:473
#10 0x00007ffff6a81fa4 in loader::stub_release (req=0x7fff4020ccc0,
    ino=1422137387, fi=0x7ffef97f9d30)
    at /data/build_modules/build/cvmfs-fuse3/cvmfs-fuse3/cvmfs/loader.cc:281
#11 0x00007ffff60d717c in do_release () from /lib64/libfuse3.so.3
#12 0x00007ffff60d943a in fuse_session_process_buf_int ()
   from /lib64/libfuse3.so.3
#13 0x00007ffff60d4b75 in fuse_do_work () from /lib64/libfuse3.so.3
#14 0x00007ffff79b814a in start_thread () from /lib64/libpthread.so.0
#15 0x00007ffff6dbaf23 in clone () from /lib64/libc.so.6

```

**Comment by HereThereBeDragons** [comment]
should be fixed with #3169
