### ISSUE TITLE
CatalogTraversal can get stuck

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3171]
Multi-threaded version of CatalogTraversal needs investigation as it can hang forever

Can be seen with T_CatalogTraversal/1.TraverseDepthFirstParallelStressSlow does not always succeed. if it fails it hangs forever
with the refactored loadcatalog #3156 this unittest always hangs

see also https://sft.its.cern.ch/jira/browse/CVM-2019

**Comment by DrDaveD** [comment]
The secondary IHEP stratum 1 just experienced a case of this on cvmfs-server-2.10.1.

**Comment by DrDaveD** [comment]
Oddly, the exact same repository (fifeuser3.opensciencegrid.org) got stuck on one of the two cvmfs-userpub machines at Fermilab one day later (May 13).

**Comment by DrDaveD** [comment]
Here's a piece of information that may help you track down the problem.

Both of the same two machines later failed snapshots on the same repository, with the following error:
```
cvmfs_swissknife: /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc7/build/BUILD/cvmfs-2.10.1/cvmfs/util/posix.cc:489: void MakePipe(int*): Assertion `retval == 0' failed.
/usr/bin/cvmfs_server: line 7528: 95105 Aborted
                 $user_shell "$(__swissknife_cmd dbg) pull -m $name         -u $stratum0
                  -w $stratum1                                           -r ${upstream}                                         -x ${spool_dir}/tmp
                       -k $public_key                                         -n $num_workers                                        -t $timeout
                            -a $retries $with_history $with_reflog
      $initial_snapshot_flag $timestamp_threshold $log_level"
```

It turned out that those two machines had a soft ulimit -n of 1024 and a hard ulimit of 4096, where other machines that had no problem had a ulimit -n of of 65536.  I increased the nofile limit on one of the machines and the snapshot completed successfully.

So that makes me wonder if there's something in the gc code that goes into a loop when running out of file descriptors.

**Comment by DrDaveD** [comment]
The same machine at FNAL got stuck on gc again on the same fifeuser3.opensciencegrid.org repository.  This time I confirmed that its naximum open file descriptors has been increased to 65536, so that theory of file descriptors affecting gc is proved false.  lsof also showed only 15 file descriptors open.  gstack on the gc looks similar to other reports:
```
Thread 3 (Thread 0x7f9500fca700 (LWP 153373)):
#0  0x00007f950380ca35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000004c358f in PopFront (this=0xdffba0) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/ingestion/tube.h:126
#2  TubeConsumer<upload::AbstractUploader::UploadJob>::MainConsumer (data=0xdffca0) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/ingestion/task.h:51
#3  0x00007f9503808ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f9502908b0d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f94f4aa7700 (LWP 154158)):
#0  0x00007f950380ca35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000047ad4f in Tube<swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::CatalogJob>::PopFront (this=this@entry=0x7fff7494cc50) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/ingestion/tube.h:126
#2  0x000000000047c968 in swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::MainProcessQueue (data=0x7fff7494cab0) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/catalog_traversal_parallel.h:209
#3  0x00007f9503808ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f9502908b0d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f9504caf8c0 (LWP 153372)):
#0  0x00007f950380a017 in pthread_join () from /lib64/libpthread.so.0
#1  0x000000000047a99c in swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::DoTraverse (this=0x7fff7494cab0) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/catalog_traversal_parallel.h:189
#2  0x000000000047b248 in swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::TraverseList (this=0x7fff7494cab0, root_catalog_list=..., type=swissknife::CatalogTraversalBase<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::kDepthFirst) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/catalog_traversal_parallel.h:145
#3  0x000000000047b429 in GarbageCollector<swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >, SmallhashFilter>::SweepReflog (this=this@entry=0x7fff7494ca30) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/garbage_collection/garbage_collector_impl.h:280
#4  0x0000000000478540 in Collect (this=0x7fff7494ca30) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/garbage_collection/garbage_collector_impl.h:211
#5  swissknife::CommandGc::Main (this=<optimized out>, args=...) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/swissknife_gc.cc:188
#6  0x0000000000414718 in main (argc=<optimized out>, argv=0x7fff7494d118) at /builddir/build/BUILD/cvmfs-2.10.1/cvmfs/swissknife_main.cc:195
```

**Comment by DrDaveD** [comment]
Thanks for the fix.  FYI I have added #3291 as a patch to rpm cvmfs-2.10.1-1.3 which is now built in the osg-development yum repo and installed on the two machines at Fermilab where we have been hitting this frequently.  I will let you know if we see the problem there again.
