### ISSUE TITLE
Garbage collection stuck on cvmfs-server-2.10.0

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3176]
Garbage collection done weekly on Saturdays on the FNAL stratum 1 servers got stuck on one server this weekend, on sw-nightlies.hsf.org.  Normally it takes 10 minutes, but we killed it after about 15 hours.  
strace showed no activity, and gstack showed the following:
```
Thread 3 (Thread 0x7f0e77fff700 (LWP 43029)):
#0  0x00007f0e82b61a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000004c2e33 in PopFront (this=0x1c12850) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/ingestion/tube.h:126
#2  TubeConsumer<upload::AbstractUploader::UploadJob>::MainConsumer (data=0x1c032f0) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/ingestion/task.h:51
#3  0x00007f0e82b5dea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f0e81c5db0d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f0e752a8700 (LWP 144975)):
#0  0x00007f0e82b61a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000047a5f3 in Tube<swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::CatalogJob>::PopFront (this=this@entry=0x7ffea73b3270) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/ingestion/tube.h:126
#2  0x000000000047c20c in swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::MainProcessQueue (data=0x7ffea73b30d0) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/catalog_traversal_parallel.h:209
#3  0x00007f0e82b5dea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f0e81c5db0d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f0e840048c0 (LWP 43015)):
#0  0x00007f0e82b5f017 in pthread_join () from /lib64/libpthread.so.0
#1  0x000000000047a240 in swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::DoTraverse (this=0x7ffea73b30d0) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/catalog_traversal_parallel.h:189
#2  0x000000000047aaec in swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::TraverseList (this=0x7ffea73b30d0, root_catalog_list=..., type=swissknife::CatalogTraversalBase<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >::kDepthFirst) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/catalog_traversal_parallel.h:145
#3  0x000000000047accd in GarbageCollector<swissknife::CatalogTraversalParallel<HttpObjectFetcher<catalog::Catalog, history::SqliteHistory, manifest::Reflog> >, SmallhashFilter>::SweepReflog (this=this@entry=0x7ffea73b3050) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/garbage_collection/garbage_collector_impl.h:280
#4  0x0000000000477db4 in Collect (this=0x7ffea73b3050) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/garbage_collection/garbage_collector_impl.h:211
#5  swissknife::CommandGc::Main (this=<optimized out>, args=...) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/swissknife_gc.cc:188
#6  0x00000000004146c8 in main (argc=<optimized out>, argv=0x7ffea73b3738) at /builddir/build/BUILD/cvmfs-2.10.0/cvmfs/swissknife_main.cc:195
```
After killing the process and catching up the snapshot, gc was run by hand and it completed in 11 minutes.

This machine was upgraded to cvmfs-server-2.10.0 (built by OSG) on January 10. In case it is relevant, there was a situation where the underlying file server got rebooted mid-week, and we had to reboot the stratum 1 server. Afterward there were many .cvmfs* files that were zero length and had to be restored.

**Comment by jblomer** [comment]
It seems that this is the same issue as [CVM-2019](https://sft.its.cern.ch/jira/browse/CVM-2019), resp. #3171. We'll raise the priority.

**Comment by DrDaveD** [comment]
Thanks for finding that link.  I knew it sounded familiar but my searches for "garbage collection" failed. I should have also tried "gc".

**Comment by DrDaveD** [comment]
Closing this one as a duplicate.
