### ISSUE TITLE
Hanging repository correlated with "local IO" errors every day

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3517]
At the ATLAS aglt2 site they have been experiencing a few nodes a day getting stuck with accesses to oasis.opensciencegrid.org.  I investigated two of the cases, and both times that repository started hanging around the same time as many "local IO" errors showing up on the atlas.cern.ch repository in /var/log/messages.  It doesn't appear as though there were disks that ran out of space.

I attach tarballs for the two nodes that each include bugreport tarballs (as much as I could collect without hanging) and some additional debugging info.  The c6* one has a little more complete information, including a bunch of stacktrace files that were collected at the time the problem started.  There was also a stacktrace shown /var/log/messages there, and in that case I showed the entire snippet of /var/log/messages during the less than 60 seconds of local IO errors, including any messages not from cvmfs.  In addition I collected my own live stack trace for the oasis.opensciencegrid.org cvmfs2 process before killing it.

[c7-2-38.aglt2.org.tgz](https://github.com/cvmfs/cvmfs/files/14387873/c7-2-38.aglt2.org.tgz)
[c6-12-25-4.aglt2.org.tgz](https://github.com/cvmfs/cvmfs/files/14387875/c6-12-25-4.aglt2.org.tgz)

**Comment by vvolkl** [comment]
I've had the chance to look at another node, where I found a stuck mount.cvmfs processes:
```
[root@c6-6-39-4 ~]# ps -efww | grep mount
root       7160      1  0 Jan11 ?        01:24:05 /usr/sbin/automount --systemd-service --dont-check-daemon
root      35808   7160  0 Mar13 ?        00:00:00 /usr/bin/mount -n -t cvmfs atlas.cern.ch /cvmfs/atlas.cern.ch
root      35809  35808  0 Mar13 ?        00:00:00 /sbin/mount.cvmfs atlas.cern.ch /cvmfs/atlas.cern.ch -n -o rw
root      35839  35809  0 Mar13 ?        00:00:00 /sbin/mount.cvmfs atlas.cern.ch /cvmfs/atlas.cern.ch -n -o rw
root     248645 246187  0 11:04 pts/3    00:00:00 grep --color=auto mount
```
The stacktrace for 35809 was 
```

#0  0x00007f62fd098740 in __read_nocancel () from /lib64/libpthread.so.0
#1  0x000000000040bdf8 in ReadPipe (fd=3, buf=buf@entry=0x7ffd75b62528, 
    nbyte=nbyte@entry=1)
    at /builddir/build/BUILD/cvmfs-2.11.2/cvmfs/util/posix.cc:516
#2  0x00000000004086f7 in BashOptionsManager::ParsePath (
    this=this@entry=0x61a8a0 <options_manager_>, 
    config_file="/cvmfs/config-osg.opensciencegrid.org/etc/cvmfs/default.conf", external=external@entry=true)
    at /builddir/build/BUILD/cvmfs-2.11.2/cvmfs/options.cc:183
#3  0x0000000000407e87 in OptionsManager::ParseDefault (
    this=this@entry=0x61a8a0 <options_manager_>, fqrn="atlas.cern.ch")
    at /builddir/build/BUILD/cvmfs-2.11.2/cvmfs/options.cc:298
#4  0x0000000000405409 in main (argc=<optimized out>, argv=<optimized out>)
    at /builddir/build/BUILD/cvmfs-2.11.2/mount/mount.cvmfs.cc:412
```
while 35839 was completely unresponsive.

**Comment by DrDaveD** [comment]
Weren't the mounts command stuck because they were waiting to hear from  cvmfs2 processes?  Did you see "local IO" errors in the log?
