### ISSUE TITLE
PullRecursion loop causing segmentation fault

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3624]
After getting past a case of #3606, a stratum 1 at FNAL repeatedly got segmentation faults when replicating from the same repository it was getting the MakePipe failures on, fifeuser3.opensciencegrid.org.  I caught it once when running it interactively with CVMFS_SERVER_DEBUG=1 and collected a backtrace.  There were over 13,000 stack frames, mostly alternating between `swissknife::CommandPull::Pull` and `swissknife::CommandPull::PullRecursion`.  Here's the beginning and ending of the trace:
```
(gdb) bt
ESC[?2004l^M#0  0x0000000000459768 in zlib::DecompressZStream2File (
    buf=<error reading variable: Cannot access memory at address 0x7fffff7fef88>
,
    size=<error reading variable: Cannot access memory at address 0x7fffff7fef80
>, strm=<error reading variable: Cannot access memory at address 0x7fffff7fef78>
,
    f=<error reading variable: Cannot access memory at address 0x7fffff7fef70>)
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/compression.cc:280
#1  0x000000000045a63e in zlib::DecompressFile2File (fsrc=0x847d40,
    fdest=0x7f3280)
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/compression.cc:650
#2  0x0000000000459caf in zlib::DecompressPath2Path (
    src="/var/spool/cvmfs/fifeuser3.opensciencegrid.org/tmp/cvmfs.zvDFn3",
    dest="/var/spool/cvmfs/fifeuser3.opensciencegrid.org/tmp/cvmfs.2p14J6")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/compression.cc:392
#3  0x000000000057746e in swissknife::CommandPull::Pull (this=0x7d7970,
    catalog_hash=..., path="")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:416
#4  0x0000000000576d76 in swissknife::CommandPull::PullRecursion (
    this=0x7d7970, catalog=0x1f96a880, path="")
...
#13176 0x0000000000576d76 in swissknife::CommandPull::PullRecursion (
    this=0x7d7970, catalog=0x9bf6d0, path="")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:313
#13177 0x0000000000577847 in swissknife::CommandPull::Pull (this=0x7d7970,
    catalog_hash=..., path="")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:472
#13178 0x0000000000576d76 in swissknife::CommandPull::PullRecursion (
    this=0x7d7970, catalog=0x9af490, path="")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:313
#13179 0x0000000000577847 in swissknife::CommandPull::Pull (this=0x7d7970,
    catalog_hash=..., path="")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:472
#13180 0x0000000000576d76 in swissknife::CommandPull::PullRecursion (
    this=0x7d7970, catalog=0x99c610, path="")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:313
#13181 0x0000000000577847 in swissknife::CommandPull::Pull (this=0x7d7970,
    catalog_hash=..., path="")
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:472
#13182 0x0000000000579c13 in swissknife::CommandPull::Main (this=0x7d7970,
    args=std::map with 12 elements = {...})
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_pull.cc:795
#13183 0x00000000005410e3 in main (argc=25, argv=0x7fffffffdee8)
    at /builddir/build/BUILD/cvmfs-2.11.3/cvmfs/swissknife_main.cc:195
```
I tried also doing strace on it, and found the catalog that it last attempted to read just before the segmentation fault and downloaded it instead by hand, but that didn't help.  It did seem that that catalog was often showing up in the snapshot log just before the fault but maybe that was just a coincidence.

I am working around the problem by taking a fresh snapshot.

**Comment by DrDaveD** [comment]
The same thing happened on the other stratum 1, and taking a fresh snapshot on each of the pair of machines worked around the problem.

I saved a copy of the data repository state on the second machine if somebody wants to try to reproduce it.  It is 36G when unpacked.

**Comment by vvolkl** [comment]
Should be fixed by #3846. Waiting for confirmation before closing

**Comment by vvolkl** [comment]
No problems of this type have been reported since.
