### ISSUE TITLE
Unresponsive mount process (lock contention?) on alma8 

### ISSUE THREAD

**Issue by vvolkl** [cvmfs/cvmfs#3650]
CMS build nodes started showing issues similar to #3628 this week.  On the node I could investigate, all repositories except cms-ib.cern.ch were working, but any attempt to read or list /cvmfs/cms-ib.cern.ch hangs - also gdb hangs when trying to attach to the mount process.

Some log excerpts below. Notably cvmfs_talk was initially still able to talk to cms-ib.cern.ch, but then also got stuck after some operations. The most interesting find was that a kill -QUIT was able to kill the stuck process and get a stacktrace in the syslog.

These nodes were updated to 2.11.4 last week, but it's not clear if that was the trigger. According to Shahzad, the incidence of this issue was far higher on alma8 than alma9. 

```
# package versions on alma8
kernel-core 4.18.0
kernel-headers 4.18.0
fuse-libs 2.9.7
fuse3-libs 3.3.0
kernel-modules 4.18.0
kernel-core 4.18.0
kernel 4.18.0
kernel-core 4.18.0
kernel 4.18.0
squashfuse 0.1.104
kernel-modules 4.18.0
kernel-modules 4.18.0
kernel-tools 4.18.0
fuse-overlayfs 1.13
squashfuse-libs 0.1.104
fuse-common 3.3.0
fuse 2.9.7
kernel 4.18.0
fuse3 3.3.0
kernel-tools-libs 4.18.0

# from dmesg
[483166.234361] R13: 000014ae970fd400 R14: 0000000000000001 R15: 000014af030ddd90
[483166.234367] INFO: task cmsRun:2060166 blocked for more than 120 seconds.
[483166.235678]       Not tainted 4.18.0-553.8.1.el8_10.x86_64 #1
[483166.236795] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[483166.238285] task:cmsRun          state:D stack:0     pid:2060166 ppid:2059397 flags:0x00000082
[483166.238288] Call Trace:
[483166.238290]  __schedule+0x2d1/0x870
[483166.238295]  schedule+0x55/0xf0
[483166.238298]  schedule_preempt_disabled+0xa/0x10
[483166.238302]  __mutex_lock.isra.11+0x349/0x420
[483166.238305]  ? __d_alloc+0x22/0x1d0
[483166.238307]  ? kmem_cache_alloc+0x13f/0x280
[483166.238313]  fuse_lock_inode+0x2f/0x40 [fuse]
[483166.238321]  fuse_lookup.part.27+0x30/0x120 [fuse]
[483166.238327]  ? __d_alloc+0x11a/0x1d0
[483166.238329]  ? d_alloc_parallel+0x9f/0x390
[483166.238332]  fuse_atomic_open+0x8c/0x120 [fuse]
[483166.238338]  path_openat+0x97f/0x1580
[483166.238341]  ? generic_file_buffered_read+0x7d0/0xbb0
[483166.238345]  ? autoremove_wake_function+0x2e/0x60
[483166.238347]  ? __wake_up_common+0x7a/0x190
[483166.238349]  do_filp_open+0x93/0x100
[483166.238352]  ? getname_flags+0x4a/0x1e0
[483166.238355]  ? __check_object_size+0xac/0x173
[483166.238358]  ? __alloc_fd+0xb1/0x150
[483166.238359]  do_sys_openat2+0x211/0x2b0
[483166.238362]  do_sys_open+0x4b/0x80
[483166.238366]  do_syscall_64+0x5b/0x1b0
[483166.238369]  entry_SYSCALL_64_after_hwframe+0x61/0xc6
[483166.238372] RIP: 0033:0x149a2ed3a784
[483166.238376] Code: Unable to access opcode bytes at RIP 0x149a2ed3a75a.
[483166.238377] RSP: 002b:00001499f2da5ab0 EFLAGS: 00000293 ORIG_RAX: 0000000000000101
[483166.238379] RAX: ffffffffffffffda RBX: 00001499b5440e00 RCX: 0000149a2ed3a784
[483166.238380] RDX: 0000000000000000 RSI: 00001499b440a6e0 RDI: 00000000ffffff9c
[483166.238381] RBP: 00001499b440a6e0 R08: 0000000000000000 R09: 0000000000000001
[483166.238382] R10: 0000000000000000 R11: 0000000000000293 R12: 0000000000000000
[483166.238384] R13: 00001499b5440e00 R14: 0000000000000001 R15: 0000149a2f158d90
[509049.865951] docker0: port 1(veth14965f0) entered blocking state


# stack of unresponsive mount process
[root@cmsbuild123 ~]# cat /proc/2495/stack
[<0>] futex_wait_queue_me+0xa3/0x100
[<0>] futex_wait+0x11f/0x210
[<0>] do_futex+0x143/0x4e0
[<0>] __x64_sys_futex+0x14e/0x200
[<0>] do_syscall_64+0x5b/0x1b0
[<0>] entry_SYSCALL_64_after_hwframe+0x61/0xc6
[root@cmsbuild123 ~]# cat /proc/2495/environ 
LANG=en_US.UTF-8INVOCATION_ID=ab7250353d724a6a85ed4097aa2cfeb6JOURNAL_STREAM=9:37014USE_MISC_DEVICE=yesTIMEOUT=0open_file_limit=20480timeout=600master_wait=10negative_timeout=60browse_mode=1logging=noneldap_timeout=-1ldap_network_timeout=8append_options=1mount_verbose=0mount_wait=-1umount_wait=12auth_conf_file=/etc/autofs_ldap_auth.confmount_nfs_default_protocol=3use_hostname_for_mounts=0disable_not_found_message=0use_ignore_mount_option=0sss_master_map_wait=0use_mount_request_log_id=0CVMFS_FQRN=cms-ib.cern.chCVMFS_CLIENT_PROFILE=CVMFS_CACHE_BASE=/var/lib/cvmfsCVMFS_QUOTA_LIMIT=10000CVMFS_TIMEOUT=5CVMFS_TIMEOUT_DIRECT=10CVMFS_STRICT_MOUNT=noCVMFS_NFILES=131072CVMFS_SHARED_CACHE=yesCVMFS_CHECK_PERMISSIONS=yesCVMFS_CLAIM_OWNERSHIP=yesCVMFS_KEYS_DIR=/cvmfs/cvmfs-config.cern.ch/etc/cvmfs/keys/cern.chCVMFS_PROXY_RESET_AFTER=300CVMFS_HOST_RESET_AFTER=1800CVMFS_MAX_RETRIES=1CVMFS_BACKOFF_INIT=2CVMFS_BACKOFF_MAX=10CVMFS_SEND_INFO_HEADER=yesCVMFS_USE_GEOAPI=noCVMFS_LOW_SPEED_LIMIT=1024CVMFS_USER=cvmfsCVMFS_MOUNT_DIR=/cvmfsCVMFS_RELOAD_SOCKETS=/var/run/cvmfsCVMFS_BASE_ENV=1CVMFS_CONFIG_REPOSITORY=cvmfs-config.cern.chCVMFS_DEFAULT_DOMAIN=cern.chCVMFS_DNS_MIN_TTL=300CVMFS_HTTP_PROXY=http://ca-proxy-meyrin.cern.ch:3128;http://ca-proxy.cern.ch:3128CVMFS_REPOSITORIES=cms-ib.cern.ch,cms.cern.ch,grid.cern.ch,projects.cern.ch,CVMFS_PAC_URLS=http://grid-wpad/wpad.dat;http://wpad/wpad.dat;http://cernvm-wpad.fnal.gov/wpad.dat;http://cernvm-wpad.cern.ch/wpad.datCVMFS_CONFIG_REPO_DEFAULT_ENV=1CVMFS_HIDE_MAGIC_XATTRS=yesCVMFS_MAGIC_XATTRS_VISIBILITY=rootonlyCVMFS_FALLBACK_PROXY=http://cvmfsbproxy.cern.ch:3126;http://cvmfsbproxy.fnal.gov:3126CVMFS_SERVER_URL=http://cvmfs-stratum-one.cern.ch/cvmfs/cms-ib.cern.ch;http://cvmfs.fnal.gov/cvmfs/cms-ib.cern.ch[root@cmsbuild123 ~]# cat /proc/2495/status
Name:	cvmfs2
Umask:	0007
State:	S (sleeping)
Tgid:	2495
Ngid:	0
Pid:	2495
PPid:	1
TracerPid:	0
Uid:	0	500	0	500
Gid:	0	498	0	498
FDSize:	16384
Groups:	 
NStgid:	2495
NSpid:	2495
NSpgid:	2494
NSsid:	2494
VmPeak:	10311720 kB
VmSize:	 9175884 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	 1228520 kB
VmRSS:	 1121532 kB
RssAnon:	 1119940 kB
RssFile:	    1592 kB
RssShmem:	       0 kB
VmData:	 2224340 kB
VmStk:	     132 kB
VmExe:	      76 kB
VmLib:	   13784 kB
VmPTE:	    2996 kB
VmSwap:	     532 kB
HugetlbPages:	       0 kB
CoreDumping:	0
THP_enabled:	1
Threads:	32
SigQ:	27/469824
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000200
SigIgn:	0000000000000a00
SigCgt:	00000001810054ef
CapInh:	0000000000000000
CapPrm:	000001ffffffffff
CapEff:	0000000000000000
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Speculation_Store_Bypass:	thread vulnerable
Cpus_allowed:	ffff
Cpus_allowed_list:	0-15
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	7
nonvoluntary_ctxt_switches:	0


# status and stack of unresponsive ls 
stuck ls process: [root@cmsbuild123 ~]# cat /proc/2315693/status
Name:	ls
Umask:	0022
State:	D (disk sleep)
Tgid:	2315693
Ngid:	0
Pid:	2315693
PPid:	1
TracerPid:	2398850
Uid:	501	501	501	501
Gid:	501	501	501	501
FDSize:	256
Groups:	500 501 
NStgid:	2315693
NSpid:	2315693
NSpgid:	2024188
NSsid:	2024188
VmPeak:	   18632 kB
VmSize:	   18632 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	    1284 kB
VmRSS:	    1284 kB
RssAnon:	     128 kB
RssFile:	    1156 kB
RssShmem:	       0 kB
VmData:	     240 kB
VmStk:	     136 kB
VmExe:	     128 kB
VmLib:	    2868 kB
VmPTE:	      84 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
CoreDumping:	0
THP_enabled:	1
Threads:	1
SigQ:	49/469824
SigPnd:	0000000000040100
ShdPnd:	0000000000024000
SigBlk:	0000000000000004
SigIgn:	0000000000000000
SigCgt:	0000000180000000
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Speculation_Store_Bypass:	thread vulnerable
Cpus_allowed:	ffff
Cpus_allowed_list:	0-15
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	2
nonvoluntary_ctxt_switches:	0
[root@cmsbuild123 ~]# cat /proc/2315693/stack
[<0>] request_wait_answer+0x12f/0x210 [fuse]
[<0>] fuse_simple_request+0x155/0x2a0 [fuse]
[<0>] fuse_send_open.isra.34+0xac/0x100 [fuse]
[<0>] fuse_do_open+0x10b/0x180 [fuse]
[<0>] fuse_open_common+0x86/0x210 [fuse]
[<0>] do_dentry_open+0x143/0x3a0
[<0>] path_openat+0x55b/0x1580
[<0>] do_filp_open+0x93/0x100
[<0>] do_sys_openat2+0x211/0x2b0
[<0>] do_sys_open+0x4b/0x80
[<0>] do_syscall_64+0x5b/0x1b0
[<0>] entry_SYSCALL_64_after_hwframe+0x61/0xc6
[root@cmsbuild123 ~]# cat /proc/2495/stack
[<0>] futex_wait_queue_me+0xa3/0x100
[<0>] futex_wait+0x11f/0x210
[<0>] do_futex+0x143/0x4e0
[<0>] __x64_sys_futex+0x14e/0x200
[<0>] do_syscall_64+0x5b/0x1b0
[<0>] entry_SYSCALL_64_after_hwframe+0x61/0xc6
```

### stacktrace in syslog after kill -QUIT
```


Aug 15 12:04:03 cmsbuild123.cern.ch cvmfs2[2490]: (cms-ib.cern.ch) --
#012Signal: 3, errno: 1, version: 2.11.4, PID: 2495
#012Executable path: /usr/bin/cvmfs2
#012
#012Thread 32 (Thread 0x7f193f7fe700 (LWP 2398518)):#12#0 0x00007f1a2c8f2ae4 in read () from /lib64/libpthread.so.0
#012#1 0x00007f1a2b787dd2 in fuse_kern_chan_receive () from /lib64/libfuse.so.2
#012#2 0x00007f1a2b78994d in fuse_ll_receive_buf () from /lib64/libfuse.so.2
#012#3 0x00007f1a2b7883e3 in fuse_do_work () from /lib64/libfuse.so.2
#012#4 0x00007f1a2c8e91ca in start_thread () from /lib64/libpthread.so.0
#012#5 0x00007f1a2bc158d3 in clone () from /lib64/libc.so.6
#012
#012Thread 31 (Thread 0x7f19dbfff700 (LWP 2315657)):#12#0 0x00007f1a2c8f2ae4 in read () from /lib64/libpthread.so.0
#012#1 0x00007f1a2b787dd2 in fuse_kern_chan_receive () from /lib64/libfuse.so.2
#012#2 0x00007f1a2b78994d in fuse_ll_receive_buf () from /lib64/libfuse.so.2
#012#3 0x00007f1a2b7883e3 in fuse_do_work () from /lib64/libfuse.so.2
#012#4 0x00007f1a2c8e91ca in start_thread () from /lib64/libpthread.so.0
#012#5 0x00007f1a2bc158d3 in clone () from /lib64/libc.so.6
#012
#012Thread 30 (Thread 0x7f193dffb700 (LWP 2310434)):#12#0 0x00007f1a2c8ee052 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#012#1 0x00007f1a2b31c8ab in catalog::AbstractCatalogManagercatalog::Catalog::ReadLock (this=)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/catalog_mgr.h:257
#012#2 0x00007f1a2b3286e2 in catalog::AbstractCatalogManagercatalog::Catalog::LookupPath (this=this@entry=0x20ae900, path=..., options=options@entry=1, #12 dirent=dirent@entry=0x7f193dffabc0)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/directory_entry.h:298
#012#3 0x00007f1a2b321e49 in cvmfs::GetDirentForInode (ino=, #12 ino@entry=113444392, dirent=dirent@entry=0x7f193dffabc0)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/cvmfs.cc:377
#012#4 0x00007f1a2b322226 in cvmfs::cvmfs_getattr (req=, #12 ino=113444392, fi=)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/cvmfs.cc:777
#012#5 0x00007f1a2b9baf92 in loader::stub_getattr (req=0x7f1a08028a10, #12 ino=113444392, fi=0x0)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/loader.cc:225
#012#6 0x00007f1a2b78b519 in do_getattr () from /lib64/libfuse.so.2
#012#7 0x00007f1a2b78b888 in fuse_ll_process_buf () from /lib64/libfuse.so.2
#012#8 0x00007f1a2b788460 in fuse_do_work () from /lib64/libfuse.so.2
#012#9 0x00007f1a2c8e91ca in start_thread () from /lib64/libpthread.so.0
#012#10 0x00007f1a2bc158d3 in clone () from /lib64/libc.so.6
#012
#012Thread 29 (Thread 0x7f193e7fc700 (LWP 2310433)):#12#0 0x00007f1a2c8ee052 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#012#1 0x00007f1a2b31c8ab in catalog::AbstractCatalogManagercatalog::Catalog::ReadLock (this=)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/catalog_mgr.h:257
#012#2 0x00007f1a2b3286e2 in catalog::AbstractCatalogManagercatalog::Catalog::LookupPath (this=0x20ae900, path=..., options=options@entry=1, #12 dirent=dirent@entry=0x7f193e7fb8c8)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/directory_entry.h:298
#012#3 0x00007f1a2b3219b1 in cvmfs::GetDirentForPath (path=..., #12 dirent=dirent@entry=0x7f193e7fb8c8)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/cvmfs.cc:427
#012#4 0x00007f1a2b32277e in cvmfs::cvmfs_lookup (req=, #12 parent=, name=)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/cvmfs.cc:578
#012#5 0x00007f1a2b9baff8 in loader::stub_lookup (req=0x7f18cc008fe0, parent=1, #12 name=0x7f18b00c4618 "SITECONF")#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/loader.cc:217
#012#6 0x00007f1a2b78b888 in fuse_ll_process_buf () from /lib64/libfuse.so.2
#012#7 0x00007f1a2b788460 in fuse_do_work () from /lib64/libfuse.so.2
#012#8 0x00007f1a2c8e91ca in start_thread () from /lib64/libpthread.so.0
#012#9 0x00007f1a2bc158d3 in clone () from /lib64/libc.so.6
#012
#012Thread 28 (Thread 0x7f19a0ff9700 (LWP 2310428)):#12#0 0x00007f1a2c8ee052 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#012#1 0x00007f1a2b31c8ab in catalog::AbstractCatalogManagercatalog::Catalog::ReadLock (this=)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/catalog_mgr.h:257
#012#2 0x00007f1a2b3289f1 in catalog::AbstractCatalogManagercatalog::Catalog::ListingStat (this=this@entry=0x20ae900, path=..., #12 listing=listing@entry=0x7f19a0ff8770)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/catalog_mgr_impl.h:557
#012#3 0x00007f1a2b324bc3 in cvmfs::cvmfs_opendir (req=, #12 ino=, fi=0x7f19a0ff8cf0)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/cvmfs.cc:948
#012#4 0x00007f1a2b9bad8c in loader::stub_opendir (req=0x7f1860009060, ino=1, #12 fi=0x7f19a0ff8cf0)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/loader.cc:239
#012#5 0x00007f1a2b78c558 in do_opendir () from /lib64/libfuse.so.2
#012#6 0x00007f1a2b78b888 in fuse_ll_process_buf () from /lib64/libfuse.so.2
#012#7 0x00007f1a2b788460 in fuse_do_work () from /lib64/libfuse.so.2
#012#8 0x00007f1a2c8e91ca in start_thread () from /lib64/libpthread.so.0
#012#9 0x00007f1a2bc158d3 in clone () from /lib64/libc.so.6
#012
#012Thread 27 (Thread 0x7f19a1ffb700 (LWP 2310426)):#12#0 0x00007f1a2c8ee052 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#012#1 0x00007f1a2b31c8ab in catalog::AbstractCatalogManagercatalog::Catalog::ReadLock (this=)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/catalog_mgr.h:257
#012#2 0x00007f1a2b3286e2 in catalog::AbstractCatalogManagercatalog::Catalog::LookupPath (this=0x20ae900, path=..., options=options@entry=1, #12 dirent=dirent@entry=0x7f19a1ffa8c8)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/directory_entry.h:298
#012#3 0x00007f1a2b3219b1 in cvmfs::GetDirentForPath (path=..., #12 dirent=dirent@entry=0x7f19a1ffa8c8)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/cvmfs.cc:427
#012#4 0x00007f1a2b32277e in cvmfs::cvmfs_lookup (req=, #12 parent=, name=)#12 at /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.11.4/cvmfs/cvmfs.cc:578
#012#5 0x00007f1a2b9baff8 in loader::stub_lookup (req=0x7f18e0023840, parent=1, #12 name=0x7f19c4072a08 "SITECONF")
```

**Comment by smuzaffar** [comment]
thankd @vvolkl for opening the issue. We noticed that this happened when cvmfs 2.11.4 client was deployed on our build nodes. We now have forced to install cvmfs 2.11.3 [a]  and things are much stable now. For some strange reason some of our nodes still install cvmfs 2.11.5 client ( some yum update or distro update does it randomly) and then cvmfs client hangs again and node is not responsive ( ssh hangs). This happens on both amla8 and alma9 nodes

[a]
cvmfs-libs-2.11.3-1.el9.x86_64
cvmfs-2.11.3-1.el9.x86_64

**Comment by smuzaffar** [comment]
On one of our alma9 build nodes cvmfs client was update to 2.11.5 [a] and then few minutes later node become unresponsive ( ssh start  hanging) and [b] is what we have in syste log during that time. Node remained in bad state for 5 days with cpu in 90% iowait state. 

[a]
```
Sep  5 12:12:41 cmsbuild903.cern.ch dnf-distro-sync[4154057]: cms-ib.cern.ch: Activating Fuse module
Sep  5 12:12:41 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Running scriptlet: cvmfs-2.11.3-1.el9.x86_64                              3/4
Sep  5 12:12:41 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Cleanup          : cvmfs-2.11.3-1.el9.x86_64                              3/4
Sep  5 12:12:42 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Running scriptlet: cvmfs-2.11.3-1.el9.x86_64                              3/4
Sep  5 12:12:42 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Cleanup          : cvmfs-libs-2.11.3-1.el9.x86_64                         4/4
Sep  5 12:12:42 cmsbuild903.cern.ch systemd[1]: Reloading.
Sep  5 12:12:42 cmsbuild903.cern.ch systemd-rc-local-generator: /etc/rc.d/rc.local is not marked executable, skipping.
Sep  5 12:12:42 cmsbuild903.cern.ch systemd[1]: Starting Send request to specified server, indicating server is alive and well...
Sep  5 12:12:42 cmsbuild903.cern.ch systemd[1]: Queuing reload/restart jobs for marked units…
Sep  5 12:12:42 cmsbuild903.cern.ch systemd[1]: nc_heartbeat.service: Deactivated successfully.
Sep  5 12:12:42 cmsbuild903.cern.ch systemd[1]: Finished Send request to specified server, indicating server is alive and well.
Sep  5 12:12:43 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Running scriptlet: cvmfs-libs-2.11.3-1.el9.x86_64                         4/4
Sep  5 12:12:43 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Verifying        : cvmfs-2.11.5-1.el9.x86_64                              1/4
Sep  5 12:12:43 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Verifying        : cvmfs-2.11.3-1.el9.x86_64                              2/4
Sep  5 12:12:43 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Verifying        : cvmfs-libs-2.11.5-1.el9.x86_64                         3/4
Sep  5 12:12:47 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  Verifying        : cvmfs-libs-2.11.3-1.el9.x86_64                         4/4
Sep  5 12:12:47 cmsbuild903.cern.ch dnf-distro-sync[4154057]: Upgraded:
Sep  5 12:12:47 cmsbuild903.cern.ch dnf-distro-sync[4154057]:  cvmfs-2.11.5-1.el9.x86_64            cvmfs-libs-2.11.5-1.el9.x86_64
Sep  5 12:12:47 cmsbuild903.cern.ch dnf-distro-sync[4154057]: Complete!
Sep  5 12:12:49 cmsbuild903.cern.ch systemd[1]: dnf-distro-sync.service: Deactivated successfully.
Sep  5 12:12:49 cmsbuild903.cern.ch systemd[1]: Finished dnf distro sync.
```

[b]
```
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: INFO: task cvmfs2:4154767 blocked for more than 122 seconds.
Sep  5 13:04:42 cmsbuild903.cern.ch kernel:      Not tainted 5.14.0-427.28.1.el9_4.x86_64 #1
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: task:cvmfs2          state:D stack:0     pid:4154767 ppid:1      flags:0x00000002
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: Call Trace:
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: <TASK>
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: __schedule+0x21b/0x550
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: schedule+0x2d/0x70
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: io_schedule+0x42/0x70
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: folio_wait_bit_common+0x120/0x340
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? xas_init_marks+0x1f/0x50
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? __pfx_wake_page_function+0x10/0x10
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: invalidate_inode_pages2_range+0x143/0x400
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: fuse_reverse_inval_inode+0x93/0xc0 [fuse]
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: fuse_notify+0x3b6/0x500 [fuse]
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: fuse_dev_do_write+0x305/0x4e0 [fuse]
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: fuse_dev_write+0x50/0x80 [fuse]
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: do_iter_readv_writev+0x127/0x190
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: do_iter_write+0x81/0x1c0
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: vfs_writev+0xae/0x170
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? __fget_light+0x9f/0x130
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? __fget_light+0x9f/0x130
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: do_writev+0x6f/0x120
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: do_syscall_64+0x5c/0x90
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? syscall_exit_work+0x103/0x130
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? syscall_exit_to_user_mode+0x22/0x40
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? do_syscall_64+0x69/0x90
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? syscall_exit_to_user_mode+0x22/0x40
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? do_syscall_64+0x69/0x90
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? syscall_exit_work+0x103/0x130
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? syscall_exit_to_user_mode+0x22/0x40
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? do_syscall_64+0x69/0x90
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? do_syscall_64+0x69/0x90
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? do_syscall_64+0x69/0x90
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: ? sysvec_apic_timer_interrupt+0x3c/0x90
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: entry_SYSCALL_64_after_hwframe+0x72/0xdc
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: RIP: 0033:0x7fc87d50368d
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: RSP: 002b:00007fc878689cd0 EFLAGS: 00000293 ORIG_RAX: 0000000000000014
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: RAX: ffffffffffffffda RBX: 0000000000000002 RCX: 00007fc87d50368d
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: RDX: 0000000000000002 RSI: 00007fc878689d50 RDI: 0000000000000018
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: RBP: 00007fc878689d50 R08: 0000000000000000 R09: 0000000000000000
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: R10: 00007ffff4581080 R11: 0000000000000293 R12: 0000000001254440
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: R13: 000000001b17e7e0 R14: 0000000000023448 R15: 0000000000251e40
Sep  5 13:04:42 cmsbuild903.cern.ch kernel: </TASK>
```

**Comment by deesto** [comment]
@smuzaffar We noted in [this issue](https://github.com/cvmfs/cvmfs/issues/3628) after much debugging and discussion that it might be best (and possibly necessary) to `killall` and `wipecache` when upgrading to the .5 release, if not force a full reboot. Your node's client cache may have already been in a bad state that can't be rectified by cache management even after the update. This has certainly been an inconvenience, but so far we have seen very few issues on our A9 nodes running the .5 client after having rolled out the patch release in this manner.
